apiVersion: gitops.k8smgmt.io/v3
kind: InfraProvisioner
metadata:
  name: i1
  project: sourav
spec:
  config:
    envVars:
    - key: AWS_ACCESS_KEY_ID
      type: Secure
      value: sealed://config.envVars.AWS_ACCESS_KEY_ID
    - key: AWS_SECRET_ACCESS_KEY
      type: Secure
      value: sealed://config.envVars.AWS_SECRET_ACCESS_KEY
    inputVars:
    - key: ami_id
      type: Plain
      value: ami-07b068f843ec78e72
    - key: instance_type
      type: Plain
      value: t2.xlarge
    secretGroups:
    - "\n\x17\n\x06bucket\x12\ravinash-rafay\n\x13\n\x06region\x12\tus-west-1\n\x18\n\x03key\x12\x11terraform/test-ip"
    version: 0.14.0
  folder:
    name: infrastructure-as-code/aws-ec2-instance
  repository: avinash-terr
  revision: master
  secret:
    name: file://artifacts/i1/sealed-secret.yaml
  type: Terraform
