apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: ss-test
  project: sourav
spec:
  agents:
  - name: sync-test
  credentials:
    password: sealed://credentials.password
    username: sourav-rafay
  endpoint: https://github.com/sourav-rafay/test.git
  options:
    caCert:
      name: ca-cert.pem
  secret:
    name: file://artifacts/ss-test/sealed-secret.yaml
  type: Git
