apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: ss-terr-cp1
  project: sourav
spec:
  active: true
  sharing:
    enabled: false
  stages:
  - config:
      action:
        action: Plan
        refresh: true
      agents:
      - name: ss-d3
      provisioner: i1
      revision: master
      type: Terraform
    name: s1
    type: InfraProvisioner
