apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: bp1
  project: sourav
spec:
  base:
    name: default
    version: 1.16.0
  defaultAddons:
    csiSecretStoreConfig:
      providers: {}
    enableIngress: false
    enableLogging: false
    enableMonitoring: false
    enableVM: false
  drift:
    enabled: false
  opaPolicy: {}
  placement: {}
  sharing:
    enabled: false
  version: "0.1"
